Fix errors with now() and date/timestamp parameters in queries
Commit 17c16074543992812ff55d7035904a3a5978183c fixed selecting
dates and timestamps for unusual values by changing the corresponding
NLS_*_FORMAT values, but ignored that these parameters also influence
processing of date and timestamp parameters.

This resulted in errors like
ERROR:  error executing query: OCIDateTimeFromText failed to convert parameter
DETAIL:  ORA-01843: not a valid month
when now() or "current_timestamp" and friends or date/timestamp
parameters were used.

Fix by factoring out deparseDate() and deparseTimestamp() from
setModifyParameters() and using these everywhere.
Date and timestamp parameters are now bound as strings.

Add some regression tests that were clearly missing.

Report by Li Hailong.