Fix queries with ten or more parameters
In createQuery(), we eliminate all parameters that don't actually occur
in the Oracle query string created.  This is done in a rather crude
fashion by searching for the parameter string in the query text.  Now
if we have ten or more parameters, there is a parameter :p1 and a
parameter :p10, and our logic will fail to eliminate :p1, because it
is a substring of :p10.  As a consequence, oracleExecuteQuery() binds
more parameters than it should, which leads to the error

    ERROR: error executing query: OCIBindByName failed to bind parameter
    DETAIL: ORA-01036: illegal variable name/number

As a fix, change the parameter names to have five digits, like :p00001
and :p00010.  That will avoid the problem.  Note that there is still a
chance of false positive matches, for example if :p00001 occurs in a
string literal.

This bug has been present from the beginning, but it became more
exposed by commit aa508080584d3fb9e6cb600e41852da63e08fec2, because
deparseExpr() now scans more of the parse tree, so it is more likely
to encounter parameters that should get eliminated later.

This patch fixes #770, reported by Cheolyeon Byun.