Fix a bug introduced with b926831356
Skipping savepoints for read-only transactions moved the
place where the "xact_level" of the connection entry is
increased in "oracleSetSavepoint", but forgot to adjust
the name of the savepoint that was used.
As a result, we set savepoint S3 instead of S2, which led
to errors like this during ROLLBACK TO SAVEPOINT:

WARNING:  AbortSubTransaction while in ABORT state
ERROR:  error rolling back to savepoint: OCIStmtExecute failed on ROLLBACK TO SAVEPOINT
DETAIL:  ORA-01086: savepoint 'S2' never established in this session or is invalid