Fix various bugs in date and timestamp handling
Oracle TIMESTAMP(0) fields caused errors like:
ERROR: invalid input syntax for type timestamp: "1977-06-09 18:00:00."
(The error is caused by the extra period at the end.)
Also, handling of dates and timestamps before Christ was broken.

Fix by choosing different Oracle format strings.
Regression tests have been changed to cover dates BC.

Report by "abiuan".